Moda.Sidebar.background = #000000
Moda.Sidebar.Title.foreground = #ffffff
Moda.ShowData.DataList.selectionBackground = #000000
Moda.ShowData.DataList.evenBackground = #ffffff
Moda.ShowData.DataList.oddBackground = #f1f1f1