Moda.Scrollbar.colour = #dbdbdb
Moda.Sidebar.background = #000000
Moda.Sidebar.Title.foreground = #ffffff
Moda.ShowData.DataList.selectionBackground = #000000
Moda.ShowData.DataList.evenBackground = #777674
Moda.ShowData.DataList.oddBackground = #4b4a48
Moda.TextField.background = #6a6a67
Moda.TextField.border = #000000
